reference/SDK: rework SDK docs,cover container SDK
flatcar-linux/flatcar-docs pull request #195
Opened 2021-12-22 15:11 UTC by t-lo

Update the developer reference documentation to cover the SDK container.

2021-12-22 16:25 UTC, krnowak reviewed
Found some typos.

2021-12-22 16:25 UTC, krnowak commented on docs/reference/developer-guides/sdk-building-production-images.md
> +[scripts-repo-ci]: https://github.com/flatcar-linux/scripts/ci-automation
That's 404.

2021-12-22 16:25 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +* Release **tags** signify speficic (past) releases, like "stable-2905.2.4" or "beta-3033.1.1". Tags are created in release branches.
```suggestion
* Release **tags** signify specific (past) releases, like "stable-2905.2.4" or "beta-3033.1.1". Tags are created in release branches.
```

2021-12-22 16:25 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +This is usually derired to prevent version muddling.
```suggestion
This is usually desired to prevent version muddling.
```

2021-12-22 16:25 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +These files contain a package’s dependencies - both build and runtime - as well as implement callbacks for downloading, patching, building, and installing a package.
```suggestion
These files contain package’s dependencies - both build and runtime - as well as implement callbacks for downloading, patching, building, and installing a package.
```

2021-12-22 16:25 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +FLatcar follows its own stabilisation process (through the Alpha - Beta - Stable channels); it's perfectly fine to unmask a package upstream considers unstable.
```suggestion
Flatcar follows its own stabilisation process (through the Alpha - Beta - Stable channels); it's perfectly fine to unmask a package upstream considers unstable.
```

2022-01-03 10:29 UTC, t-lo commented on docs/reference/developer-guides/sdk-building-production-images.md
> +[scripts-repo-ci]: https://github.com/flatcar-linux/scripts/ci-automation
```suggestion
https://github.com/flatcar-linux/scripts/tree/main/ci-automation
```

2022-01-03 17:38 UTC, pothos commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Keeping `version.txt`,and submodules in sync, updating version strings, and generating version tags is one of the main concerns of the build automation scripts.
What commands should be used to set the new submodule references? I want to add them to https://github.com/flatcar-linux/scripts/blob/main/tag_release to make sure we update them from now on even if we didn't make the switch.

2022-01-04 09:00 UTC, t-lo commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Keeping `version.txt`,and submodules in sync, updating version strings, and generating version tags is one of the main concerns of the build automation scripts.
There are library functions for this; should be straightforward. We need 4 or 5 inputs depending on what we are releasing. Please note that the functions only care about the `scripts` repo so they expect either commit IDs or tags that already exist in these repos. Furthermore, the scripts only handle tagging, not branching. It is expected that the `scripts` repo is already on the correct branch.

For new major releases:
1. coreos-overlay commit-ish, tag, or branch
2. portage-stable commit-ish, tag, or branch
3. new SDK version number (to be used for both SDK and OS)
4. new release version tag name (channel + version number)

For channel propagation and other incremental releases that do not introduce a new major version we additionally need
4. new OS image version number

In the scripts repo, run
```shell
source sdk_lib/sdk_container_common.sh
source ci-automation/ci_automation_common.sh

update_submodules <coreos-overlay commit-ish> <portage-stable commit-ish>

create_versionfile <SDK-version> [<os-version>]

update_and_push_version <release-tag>
```

e.g. for a new Alpha-3110 based on the current main branches:
```shell
source sdk_lib/sdk_container_common.sh
source ci-automation/ci_automation_common.sh

update_submodules main main
create_versionfile 3110.0.0
update_and_push_version alpha-3110.0.0
```

Or for a Beta-3110.1.0 based on the above Alpha:
```shell
source sdk_lib/sdk_container_common.sh
source ci-automation/ci_automation_common.sh

update_submodules flatcar-3110 flatcar-3110
create_versionfile 3110.1.0
update_and_push_version beta-3110.1.0
```

2022-01-04 11:11 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +These files contain a package’s dependencies - both build and runtime - as well as implement callbacks for downloading, patching, building, and installing a package.
I'd say that the "a" article is bound to the "dependencies" word (and since "dependencies" is plural, it shouldn't have any indefinite article), not to "package's". But not an expert on articles. Anyway, I wouldn't go with "packages' dependencies", because the sentence is about a single package. So how about:

```suggestion
These files contain dependencies of a package - both build and runtime - as well as implement callbacks for downloading, patching, building, and installing the package.
```

2022-01-04 12:00 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +On the host outside the container, the image(s) built are located in `__build__/images/...`.
```suggestion
On the host outside the container, the image(s) built are located in `__build__/images/…`.
```

2022-01-04 12:01 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +### A brief introduction to Gentoo how it relates to the SDK
I think an "and" is missing here:

```suggestion
### A brief introduction to Gentoo and how it relates to the SDK
```

2022-01-04 12:02 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +While the Flatcar SDK can be understood as a Gentoo derivate, the OS image is special.
```suggestion
While the Flatcar SDK can be understood as a Gentoo derivative, the OS image is special.
```

2022-01-04 12:08 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +~/trunk/src/scripts $ vim ../third_party/portage-stable/<group>/<package>/<package-version>.ebuild
I'd say that this is a "no no". Instead, the preference is to modify the `package.accept_keywords` in coreos-overlay, so the modification won't be lost when we sync the portage-stable with gentoo next time. So maybe:
```suggestion
# optional - unmask package
~/trunk/src/scripts $ vim ../third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
```

2022-01-04 12:16 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +To proceed, remove the architecture mask in the ebuild file (remove the `~` - for example, change `~arm64` to `arm64`) and re-run emerge.
In the same vein as above:
```suggestion
To proceed, add the package name and version, and its masked architectures to the `package.accept_keywords` file inside the `coreos` profile. Which `package.accept_keywords` file should be updated depends on couple factors - whether it is needed for both SDK and OS image or only for SDK or only for OS image, whether it is needed for both AMD64 and ARM64 images, or only for AMD64 or only for ARM64. Please refer to `README.md` in coreos-overlay for a summary about profiles
```

2022-01-04 12:19 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The Flatcar Linux kernel build is split over multiple gentoo ebuild files which all reside in <code>[coreos-overlay/sys-kernel/](https://github.com/kinvolk/coreos-overlay/tree/main/sys-kernel)</code>
Won't this work?

```suggestion
The Flatcar Linux kernel build is split over multiple gentoo ebuild files which all reside in [`coreos-overlay/sys-kernel/`](https://github.com/kinvolk/coreos-overlay/tree/main/sys-kernel):
```

2022-01-04 12:53 UTC, t-lo commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Versioning is controlled by the [`version.txt` file in the scripts repo](https://github.com/flatcar-linux/scripts/blob/main/sdk_container/.repo/manifests/version.txt) as well as via the commit pointe
Absolutely. I just left it there to get a first iteration of the containerised SDK / versioned git submodules out. One of the design goals of that first iteration was to reproduce *exactly* what users are used to from the `cork` SDK, which included putting the versionfile to a well-known place.
We can absolutely move it elsewhere in a follow-up operation; I feel there's a lot of room for more simplifications after we have established the groundwork.

2022-01-04 12:55 UTC, t-lo commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Each of the scripts contains documentation of the INPUTs and OUTPUTs of the respective build step:
It's all-caps in the scripts' documentation, but I agree to user lowercase here for readability.

2022-01-04 12:56 UTC, t-lo commented on docs/reference/developer-guides/sdk-tips-and-tricks.md
> +...
```suggestion
…
```

2022-01-04 13:02 UTC, t-lo reviewed
Need to revert `.md` fixes to documentation URIs since since the final, rendered docs don't use `.md` in the URI.

2022-01-04 13:02 UTC, t-lo commented on docs/reference/developer-guides/sdk-building-production-images.md
> +[mod-cl]: sdk-modifying-flatcar.md
```suggestion
[mod-cl]: sdk-modifying-flatcar
```

2022-01-04 13:02 UTC, t-lo commented on docs/reference/developer-guides/sdk-tips-and-tricks.md
> +[mod-cl]: sdk-modifying-flatcar.md
```suggestion
[mod-cl]: sdk-modifying-flatcar
```

2022-01-04 13:06 UTC, krnowak commented
> Need to revert `.md` fixes to documentation URIs since since the final, rendered docs don't use `.md` in the URI.

Meh. Maybe the renderer could be made smarter by dropping those `.md` extensions. Anyway, not a part of this PR, but thanks for letting me know.

2022-01-04 13:29 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +~/trunk/src/scripts $ vim ../third_party/portage-stable/<group>/<package>/<package-version>.ebuild
Agreed, makes sense - in particular since we're striving for full alignment and potential deprecation of portage-stable.

2022-01-04 14:46 UTC, pothos commented
More a meta comment: when is a good point to merge this? Currently we didn't switch over to it in Jenkins nor do the releases have the right submodule commits pinned, I think at least the submodule references updates should be automated for the main and maintenance branches and done for the release tags.

2022-01-04 15:03 UTC, pothos commented
> Updating the submodule pinning as well as tagging releases is already automated - and used every night for the containerised nightlies - we just need to start using it for releases.

The `flatcar-3033` branch on scripts has an outdated reference for the coreos-overlay submodule, it looks like we need add the missing automation for this first.

2022-01-04 15:16 UTC, t-lo commented
> > Updating the submodule pinning as well as tagging releases is already automated - and used every night for the containerised nightlies - we just need to start using it for releases.
> 
> The `flatcar-3033` branch on scripts has an outdated reference for the coreos-overlay submodule, it looks like we need add the missing automation for this first.

Yes, because it's a branch, and the containerised CI automation only cares about tags. So if you e.g. check out the tag `stable-3033.2.0` then you'll get coreos-overlay and portage-stable in the versions released with 3033.2.0.

The nightly builds in the CI also pull the latest submodule branches before tagging, but nightly tags aren't part of a branch. So if you e.g. check out `stable-3033.2.0-nightly-20220104-0139` you will get the state of tonight's `flatcar-3033` branches. These tags (and the respective commits) aren't part of any branch (only the tags are pushed) to prevent nightlies from polluting the scripts branches with new commits every night. 

If we're discussing auto-updating the *branches*, this doesn't need to be a CI automation thing but could even be a github action in the scripts repo: any update of a branch in either coreos-overlay or portage-stable would cause the respective branch of the same name in scripts (if it exists) to automatically update its submodule, copying the submodule's commit message.

2022-01-04 15:56 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +If no architecture is specified then AMD64 will be used by default.
Please, let's keep these two sentences about the distro package, the new NOTE below is too short and sounds like the user would have to just create this file.

2022-01-04 16:04 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
I think this needs more info on how to make sure that it is set up. In the tips and tricks all the `set_version` commands are removed and the user is left without any info on how to set the package cache up, be it for the maintenance branch or the main branch.

2022-01-04 17:07 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
They should not need to since information on the binary caches is included in the SDK container, which itself is versioned. `set_version` disappeared because it is replaced (implicitly) by checking out the correct branch or tag of the scripts repo. 

It works like this:
1. check out version A, update submodules
2. `./run_sdk_container` will read the versionfile, use the correct SDK container image for version A
3. `./build_packages` in the container will use the correct bincache for version A.

Now, to switch versions, one would:
1. check out version B, update submodules
2. `./run_sdk_container` now uses a different SDK container image - for version B
3. `./build_packages` in the container will use the bincache for version B.

Additionally, the containers for version A and B will be named accordingly (the container name contains OS and SDK version) - so one could switch back and forth between versions by just checking out the respective `scripts` branch, and never lose intermediate build artifacts (as long as the container is not deleted by the user).

2022-01-04 17:10 UTC, t-lo commented
Addressed @pothos feedback:
-  add documentation on ensuring the [release branch tips of submodules are current](https://github.com/flatcar-linux/flatcar-docs/pull/195#issuecomment-1004886030)
- make qemu / binfmt-misc documentation more elaborate and prominent for cross-compiling.

2022-01-04 17:15 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
Is there something I'm missing that `set_version` does which couldn't be done by using the plain versionfile from `scripts`?

2022-01-04 17:18 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
Ok, so the idea would be to publish nightly SDK containers for the main and the maintenance branches? Maybe without building the SDK since it doesn't need to be rebuilt for maintenance branches?

2022-01-04 17:18 UTC, pothos commented on docs/reference/developer-guides/sdk-building-production-images.md
> +git submodules update --init --recursive
```suggestion
git submodule update --init --recursive
```

2022-01-04 17:22 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +Check if your distro has support for aarch64 in `binfmt-misc` already; on e.g. Fedora there's an `qemu-aarch64` entry in `/proc` for that (the name of the proc file may vary across distributions thou
```suggestion
Check if your distro has a `qemu-user-static` package that you can install or whether it has support for aarch64 in `binfmt-misc` already; on e.g. Fedora there's an `qemu-aarch64` entry in `/proc` for that (the name of the proc file may vary across distributions though):
```

2022-01-04 17:28 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
Yes, that would be the idea. The containerised nightly job for main already builds the SDK container and credentials for pushing from CI to ghcr.io are in place (but currently unused) - it's a one-line change to publish after building.

Maintenance (release) branches don't need a new SDK (made a mistake in my first comment and updated it); the versionfile should determine the bincache URL.

2022-01-05 10:16 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
While this is not done I suggest to keep the `set_version` docs around for getting binary packages when working on the main/maintenance branches

2022-01-05 10:20 UTC, pothos commented
This effectively removes the cork docs which to me means that we should try to address the remaining pain points before the users run into them (the last hindrance due to the GCS bucket issue blocked people for a month or so and now we can be happy that all is calm again).

Beside the mentioned nightly binary package topic and the automation for release tagging, I think we should also consider Podman support, even if it's just by having a big warning in the docs that this here won't work when the Fedora `docker` wrapper script for Podman is used.

2022-01-05 10:58 UTC, t-lo commented
> This effectively removes the cork docs which to me means that we should try to address the remaining pain points before the users run into them (the last hindrance due to the GCS bucket issue blocked people for a month or so and now we can be happy that all is calm again).

Do we expect users to base their work on `main`? The main branch is regularly broken and that will prevent folks from even getting a base image built locally (i.e. w/o modifications). For release / maintenance branches, packages are available on [mirror.flatcar-linux](https://mirror.release.flatcar-linux.net/).

If we want to make working on the main branch (and using nightlies) more accessible we might want to provide an `alpha-next` binary package cache via [mirror.flatcar-linux](https://mirror.release.flatcar-linux.net/) and wire the nightly builds to use that.

> Beside the mentioned nightly binary package topic and the automation for release tagging, I think we should also consider Podman support, even if it's just by having a big warning in the docs that this here won't work when the Fedora `docker` wrapper script for Podman is used.

IIRC there wasn't much change needed to make `podman` work so why don't we just detect `podman` and add a respective option in [`run_sdk_container`](https://github.com/flatcar-linux/scripts/blob/main/run_sdk_container#L94-L127)?

Tagging commands (with examples) are documented [here](https://github.com/flatcar-linux/flatcar-docs/pull/195#discussion_r777918400).

2022-01-05 11:06 UTC, pothos commented
A maintenance branch is something like `flatcar-3033` which I would say also benefits from configuring nightly binary packages from bucket.release.flatcar-linux.net.

2022-01-05 12:20 UTC, pothos commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Keeping `version.txt`,and submodules in sync, updating version strings, and generating version tags is one of the main concerns of the build automation scripts.
This is not really what we do for the release process, a branch gets created for a new major release first, we don't use `main` to tag the Alpha.
I would say we should not just push a lone tag but actually have it be a commit first on the release maintenance branch.

2022-01-05 13:27 UTC, pothos commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Keeping `version.txt`,and submodules in sync, updating version strings, and generating version tags is one of the main concerns of the build automation scripts.
I've filed a PR now for our release tooling: https://github.com/flatcar-linux/flatcar-build-scripts/pull/91

2022-01-05 14:19 UTC, pothos commented
> IIRC there wasn't much change needed to make `podman` work so why don't we just detect `podman` and add a respective option in [`run_sdk_container`](https://github.com/flatcar-linux/scripts/blob/main/run_sdk_container#L94-L127)?

Draft in https://github.com/flatcar-linux/scripts/pull/199

2022-01-05 15:44 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ ./run_sdk_container -t
This fails if it was run once and the `version.txt` got created:
```
Error: error creating container storage: the container name "flatcar-sdk-all-3087.0.0_os-alpha-3066.0.0-52-g1933bf20" is already in use
```

2022-01-05 15:45 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ ./run_sdk_container -t
adding `-n NAME` as mentioned later in the docs gives the same error

2022-01-05 15:50 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ ./run_sdk_container -t
ah, it's the `^/` not working with podman...

2022-01-05 16:14 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ ./run_sdk_container -t
Interesting - could you please `set -x` at the top of `run_sdk_container` and provide the output? It works here...
(Also - is that with Docker or with Podman?)

2022-01-05 16:33 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ ./run_sdk_container -t
It was with Podman, pushed a fix in https://github.com/flatcar-linux/scripts/pull/199 by leaving the `^/` prefix out

2022-01-05 17:22 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ ./run_sdk_container -t
Good catch - most interestingly I just added the regex today to fix something else: https://github.com/flatcar-linux/scripts/pull/196

2022-01-05 18:24 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
> the other [solution] is that we can use the new OS version to overwrite the contents in `make.conf`

Thinking again this (overwriting the portage make.conf binhost when the OS version file gets created) is the only real solution because the current behavior is not save for releases either - they could end up reusing the initial major version binary packages instead of rebuilding all of them (didn't check if this is already the case on the nightly test job in jenkins).

2022-01-05 18:31 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
> Thinking again this (overwriting the portage make.conf binhost when the OS version file gets created) is the only real solution because the current behavior is not save for releases either - they could end up reusing the initial major version binary packages instead of rebuilding all of them (didn't check if this is already the case on the nightly test job in jenkins).

That's a great catch - I'll have a look at adding this to [sdk_entry.sh](https://github.com/flatcar-linux/scripts/blob/main/sdk_lib/sdk_entry.sh) so the container's `make.conf` is always aligned with the versionfile.

2022-01-05 20:06 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
@pothos https://github.com/flatcar-linux/scripts/pull/201

2022-01-06 09:58 UTC, t-lo commented
I'll update this pr / the docs to discuss `checkout` if we can get the PR merged: https://github.com/flatcar-linux/scripts/pull/202

2022-01-06 18:55 UTC, t-lo commented
Rebased on latest "main".

2022-01-07 15:20 UTC, t-lo commented
Updated to discuss https://github.com/flatcar-linux/scripts/pull/202 (which is now merged) as well as call out podman and docker as supported runtimes.

2022-01-07 15:43 UTC, pothos commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Versioning is controlled by the [`version.txt` file in the scripts repo](https://github.com/flatcar-linux/scripts/blob/main/sdk_container/.repo/manifests/version.txt) as well as via the commit pointe
Maybe a symlink from `/version.txt` could help? For now people will notice the file when it gets modified automatically and shows up red in `git status`

2022-01-07 15:47 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ git clone https://github.com/flatcar-linux/scripts.git
```suggestion
$ git clone --recurse-submodules https://github.com/flatcar-linux/scripts.git
```
I would always use this in the docs for people to be aware that submodules are needed (even if we have automation to fetch them when they are missing)

2022-01-07 15:49 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +$ git clone https://github.com/flatcar-linux/scripts.git
```suggestion
$ git clone --recurse-submodules https://github.com/flatcar-linux/scripts.git
```

2022-01-07 15:56 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +This wikk check out the branch or tag in the top-level `scripts` directory and update the submodules, depending on wheter a branch or tag was specified:
```suggestion
This will check out the branch or tag in the top-level `scripts` directory and update the submodules, depending on wheter a branch or tag was specified:
```

2022-01-07 15:59 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +It's likely this won't *actually* build the packages but rather download pre-built packages from the Flatcar binary package cache.
```suggestion
Beware, it's likely this won't *actually* build the packages but rather download pre-built packages from the Flatcar binary package cache (see below on how to force-rebuild a package that you modified).
```

2022-01-07 16:01 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +1. flatcar-scripts (the directory you're in) contains high-level build scripts to build all packages for an image, to build an image, and to bootstrap an SDK.
```suggestion
1. `scripts` (the directory you're in) contains high-level build scripts to build all packages for an image, to build an image, and to bootstrap an SDK.
```

2022-01-07 16:04 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +~/trunk/src/scripts $ ../build/images/amd64-usr/latest/flatcar_production_qemu.sh &
The qemu scripts may write to the terminal, I would not use `&` here but rather recommend the user to open a new terminal tab for SSH outside of this SDK container.

2022-01-07 16:05 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +~/trunk/src/scripts $ ../build/images/amd64-usr/latest/flatcar_production_qemu.sh &
Actually I would do both outside the SDK container since it's easier to pass an Ignition config to the qemu script this way.

2022-01-07 16:59 UTC, t-lo commented on docs/reference/developer-guides/sdk-building-production-images.md
> +Versioning is controlled by the [`version.txt` file in the scripts repo](https://github.com/flatcar-linux/scripts/blob/main/sdk_container/.repo/manifests/version.txt) as well as via the commit pointe
I'll at least add a note to the "Modifying OS images" doc so people are aware of the issue and know what to do.

2022-01-07 17:14 UTC, t-lo commented
Addressed @pothos ' feedback: call out the role of the versionfile and how to handle it, and start the qemu VM on the host, not inside of the container.

2022-01-07 17:40 UTC, pothos commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
With https://github.com/flatcar-linux/scripts/pull/209 I think I should be happy with the reached state and we can resolve this, maybe it's good to tell people how to get the latest nightly `version.txt` from a tag with `git show REF:sdk_container/…/version.txt` until we push it each night to the maintenance/main branch

2022-01-07 18:33 UTC, krnowak requested changes

2022-01-07 18:33 UTC, krnowak commented on docs/reference/developer-guides/sdk-building-production-images.md
> +   b. then, from the image from 2.a, generate from scratch 3 container images - "all", "amd64", and "arm64" with the respective board support included.
Is there somewhere a rendering of this document available? Because apparently github markdown does not support `a.` or `a)`, only `1.` or `1)`. And the nested ordered list uses roman numerals. So:
```suggestion
   1. build amd64 and arm64 toolchains and related board support
   2. then, from the image from 2. i., generate from scratch 3 container images - "all", "amd64", and "arm64" with the respective board support included.
```

2022-01-07 18:33 UTC, krnowak commented on docs/reference/developer-guides/sdk-tips-and-tricks.md
> +After entering the SDK container for the first time (or after re-creating it , you can set user `core`'s password:
```suggestion
After entering the SDK container for the first time (or after re-creating it), you can set user `core`'s password:
```

2022-01-07 18:33 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +Common ebuild functions shared across many packages are implemented via classes (in `eclass/`) which can be inherited by package ebuilds.
```suggestion
Common ebuild functions shared across many packages are implemented via eclasses (in `eclass/`) which can be inherited by package ebuilds.
```

2022-01-07 18:33 UTC, krnowak commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +To proceed, add the package name and version, and its masked architectures to the `package.accept_keywords` file inside the `coreos` profile. Which `package.accept_keywords` file should be updated de
```suggestion
To proceed, add the package name and version, and its masked architectures to the `package.accept_keywords` file inside the `coreos` profile. Which `package.accept_keywords` file should be updated depends on couple factors - whether it is needed for both SDK and OS image or only for SDK or only for OS image, whether it is needed for both AMD64 and ARM64 images, or only for AMD64 or only for ARM64. Please refer to `README.md` in coreos-overlay for a summary about profiles.
```

2022-01-07 18:56 UTC, t-lo commented on docs/reference/developer-guides/_index.md
> +* [Vending production images / CI integration][production-images]
:rofl:

2022-01-07 18:58 UTC, t-lo commented on docs/reference/developer-guides/sdk-modifying-flatcar.md
> +The command should download most packages from our binary cache - speeding up the "build" - since we are basing this on an existing release.
Good point, I'll make a mental note to update the SDK docs with instructions how to use the nightly tags after flatcar-linux/scripts#209 is merged and our CI is updated.

2022-01-07 19:00 UTC, t-lo commented
Addressed feedback / added suggestions. Thank you @pothos and @krnowak for all your great help!

2022-01-07 19:06 UTC, pothos approved these changes

2022-01-10 07:26 UTC, merged

2022-01-10 12:37 UTC, krnowak commented on docs/reference/developer-guides/_index.md
> +* [Vending production images / CI integration][production-images]
Hm, is actually "Vending" desired here? I thought it should remain as "Building".