reference/supply-chain: Add document on supply chain security / SLSA levels
flatcar-linux/flatcar-docs pull request #249
Opened 2022-06-17 16:49 UTC by t-lo

This change adds a document on Flatcar's supply chain security and match respective SLSA levels.

**NOTE** that statements in this doc are only made with respect to the new "ci-automation" pipeline and containerised builds. The legacy pipeline has a significantly lower level of SLSA compliance.

2022-06-22 09:06 UTC, marga-kinvolk commented on docs/reference/supply-chain.md
> +#### SLSA Thread model and requirements
This should be Threat not Thread

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +   This includes validating our inputs / upstreams, securing our builds, and ensuring attestability of our images and update payloads.
```suggestion
   This includes validating the build pipeline's inputs / upstreams, securing the build process, and ensuring attestability of the resultant images and update payloads.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +   This includes validating signatures of our images by our users / their provisioning automation, validating update payloads by our update client, and verifying integrity during the boot process.
```suggestion
   This includes validating signatures of Flatcar images by end users (or their provisioning automation), validating update payloads by the Flatcar update client, and verifying integrity during the boot process.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Flatcar builds its supply chain security on a number of basic concepts which, in summary, provide the foundation for securing our supply chain.
```suggestion
Flatcar builds its supply chain security on a number of basic concepts which, in summary, provide the foundation for securing the entire Flatcar supply chain.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +These foundational concepts fall into one of the two areas lined out above.
```suggestion
These foundational concepts fall into one of the two areas outlined above.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Flatcar release images and related artifacts are signed at build time (on the secure build infrastructure) with a 4096 bit GPG RSA key.
```suggestion
Flatcar release images and related artifacts are automatically signed at build time (on the secure build infrastructure) with a 4096 bit GPG RSA key.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Flatcar release images and related artifacts are signed at build time (on the secure build infrastructure) with a 4096 bit GPG RSA key.
(if this is correct?)

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Access to the image signing key is restricted to core maintainers.
where is the concept of "core maintainer" defined? does it map to a github team?

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +   Write access to repositories is limited to trusted group of core Flatcar maintainers.
where is this set of "trusted" group or core maintainers defined? is that a subset of the core maintainers mentioned above? (are the other core maintainers not trusted?)

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +   All changes are reviewed by at least one maintainer before merge.
is this enforced? or more of a guideline?

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Access to the infrastructure is limited to a small number of core maintainers and is reviewed regularly.
is this a subset of the "core maintainers" mentioned above? if so, what is that subset? how's it defined?

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Access to the infrastructure is limited to a small number of core maintainers and is reviewed regularly.
(in other words, to be more explicit, I think these separate sets of people need defining somewhere)

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +The OS image (and optionally, SDK) build and artifact signing is performed on hardened, secure build infrastructure.
what does "hardened, secure" actually mean? I read that as fluff without more detail. a dedicated machine (not a VM) in a secure, access-controlled Equinix Metal data center -- now that's more specific.

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +      The image is then signed with a key stored on a HSM, in an air-gapped environment so the key is never exposed.
```suggestion
      The image is then signed with a key stored on a hardware security module (HSM), in an air-gapped environment so the key is never exposed to the internet. The HSM is stored in a combination-locked safe.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +We further assess the authenticity of all OS binaries - which reside on a separate, read-only partition - at each boot.
```suggestion
Further, Flatcar assesses the authenticity of all OS binaries - which reside on a separate, read-only partition - at each boot.
```

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +We further assess the authenticity of all OS binaries - which reside on a separate, read-only partition - at each boot.
(is this the case? can you say anything more specific than "flatcar" here? which part of flatcar does that authenticity check? how?)

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +- Provide user-verifiable provenance of Flatcar's supply chain security.
Needs more text about how we're aiming to meet SLSA Level 4, and all the steps required to do that, and that we're actively working on that.

2022-06-27 15:47 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +To further enhance attestability and supply chain security we consider the below (non-exhaustive) list of improvements for Flatcar in the future.
create github issues for each and link from here

2022-07-27 09:42 UTC, t-lo commented on docs/reference/supply-chain.md
> +Access to the image signing key is restricted to core maintainers.
For Flatcar, yes. Core maintainers / trusted individuals are mentioned in SLSA without a clear definition (as the standard is work-in-progress).

2022-07-27 09:43 UTC, t-lo commented on docs/reference/supply-chain.md
> +The OS image (and optionally, SDK) build and artifact signing is performed on hardened, secure build infrastructure.
Good point, will rephrase.

2022-07-27 09:45 UTC, t-lo commented on docs/reference/supply-chain.md
> +      The image is then signed with a key stored on a HSM, in an air-gapped environment so the key is never exposed.
The combination lock does not apply, everything else makes sense. Will rephrase.

2022-07-27 10:32 UTC, t-lo commented on docs/reference/supply-chain.md
> +2. The update image and its (manually generated) signature are uploaded to the update server by the person who performed the manual signing step.
We don't. This is the build infrastructure access lined out above. However, anyone without access to the HSM could not generate a valid signature, so the update would be rejected by clients.

2022-07-27 10:41 UTC, t-lo commented on docs/reference/supply-chain.md
> +   All changes are reviewed by at least one maintainer before merge.
It's a process we follow but do not enforce (though SLSA does not state anything about enforcing). We have a tracking issue to enforce this, which in turn will need some modifications to our build automation: https://github.com/flatcar-linux/Flatcar/issues/815

2022-08-25 06:21 UTC, t-lo commented
@ahrkrak Ready for another round. I elaborated on the SLSA l4 gaps and ensured we have tracking tickets for all these.

2022-09-02 10:39 UTC, ahrkrak requested changes

2022-09-02 10:39 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +
I don't think O unambiguously means "doesn't support" - I think "–" more clearly suggests that. And added note numbers in the table.

2022-09-02 10:39 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +Building on the foundational concepts outlined above Flatcar builds its supply chain security.
```suggestion
Flatcar builds its supply chain security on the foundational concepts outlined above.
```

2022-09-02 10:39 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +   All changes are reviewed by at least one maintainer before merge.
OK, can leave this text as is then. Would be good to enforce it if possible (and I'd personally like SLSA to specify enforcement).

2022-09-02 10:39 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +
Also, shouldn't the table have a key? Even though it's relatively simple - see the Suse doc for an example.

2022-09-02 10:39 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +### Future improvements
Where is the plan to address the "Common - Superusers" gap?

2022-09-02 10:39 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +3. Common - Security: The SLSA requirement is TBD, hence not well defined.
Are we being too harsh on ourselves here? Suse claim compliance with the following statement: "Red team scans for vulnerabilities, build team patches build environment. Machine identity is enforced, user isolation by policy."

I'm not sure TPM is in scope, although we might want to flag it as an area we're working on to go BEYOND the minimum requirements of SLSA...

2022-09-02 13:56 UTC, t-lo commented on docs/reference/supply-chain.md
> +
I used "o" for "best effort" - builds are reproducible but volatile parts of the binary (like timestamps and users) change, and we don't currently have tooling in place that honors this (and skips respective sections of the binaries). I've merged your proposed "-" for the time being.

By key you mean anchor, so we can link it?

2022-09-02 14:03 UTC, t-lo commented on docs/reference/supply-chain.md
> +3. Common - Security: The SLSA requirement is TBD, hence not well defined.
Though we ensure common security practices we don't proactively validate security of our infrastructure (e.g. by making efforts to compromise it). 
And, while unfinished, the SLSA requirements strongly hint at a verifiable secure boot chain without gaps (i.e. extending attestability to the OS hosting the builds). SuSE's statement does not include any of this and seems very weak; it's the first thing I'd attack when reading their self-declaration critically.

2022-09-02 14:04 UTC, t-lo commented on docs/reference/supply-chain.md
> +### Future improvements
That's a larger endeavor that needs its own design phase - almost like a roadmap item - so a tracking issue won't cut it. but it's clearly missing here. I will add a paragraph on this.

2022-09-09 09:29 UTC, ahrkrak commented on docs/reference/supply-chain.md
> +   This will address the SLSA Security / Superusers requirement.
```suggestion
   This will address the "Security - Superusers" requirement.
```

2022-09-09 09:30 UTC, ahrkrak approved these changes
lgtm

2022-09-09 09:31 UTC, merged